export const TAG_META = {
  snowboard: { color: '#818cf8', bg: '#1e1b4b', label: '🏂 Snowboard' },
  ski:       { color: '#38bdf8', bg: '#0c2a3d', label: '⛷️ Ski' },
  photo:     { color: '#fbbf24', bg: '#2d1f00', label: '📷 Photo' },
  video:     { color: '#f87171', bg: '#2d0a0a', label: '🎬 Video' },
  drone:     { color: '#a78bfa', bg: '#1d0f3d', label: '🚁 Drone' },
  model:     { color: '#f472b6', bg: '#2d0a1e', label: '✨ Model' },
  'off-road':{ color: '#34d399', bg: '#002d1c', label: '🔥 Off-Road' },
};

export const creators = [
  {
    id: 1,
    name: 'Jake Morrison',
    initials: 'JM',
    primaryTag: 'snowboard',
    lat: 39.197,
    lng: -120.235,
    location: 'Palisades Tahoe, CA',
    rating: 4.9,
    reviewCount: 87,
    tags: ['snowboard', 'photo', 'video'],
    bio: '10+ years shooting action sports in the Sierra Nevada. Specialist in backcountry snowboard edits, powder cinematics, and lifestyle stills. Worked with Burton, Volcom, and Outside Magazine.',
    gear: [
      'Sony A7R V (primary)',
      'Canon R5 (backup)',
      'Canon 70–200mm f/2.8L IS III',
      'Sigma 35mm f/1.4 Art',
      'DJI RS 3 Pro gimbal',
      'GoPro Hero 12 Black',
    ],
    rates: { halfDay: 450, fullDay: 800 },
    // schedule[0] = today (Mar 14), schedule[6] = Mar 20
    schedule: [true, true, false, true, true, false, true],
  },
  {
    id: 2,
    name: 'Sierra Chen',
    initials: 'SC',
    primaryTag: 'drone',
    lat: 39.274,
    lng: -120.122,
    location: 'Northstar, CA',
    rating: 5.0,
    reviewCount: 43,
    tags: ['ski', 'drone', 'video'],
    bio: 'Aerial specialist and ski filmmaker. FAA Part 107 certified FPV drone operator. Known for cinematic wide passes and high-speed chase shots through tight trees.',
    gear: [
      'DJI Mavic 3 Pro (aerial)',
      'Custom FPV 5" freestyle build',
      'RED Komodo-X (ground)',
      'Sigma 18–35mm f/1.8 Art',
      'DJI Goggles 3',
    ],
    rates: { halfDay: 600, fullDay: 1100 },
    schedule: [false, true, true, true, false, true, true],
  },
  {
    id: 3,
    name: 'Zara Rhodes',
    initials: 'ZR',
    primaryTag: 'model',
    lat: 38.935,
    lng: -119.940,
    location: 'Heavenly / South Lake Tahoe',
    rating: 4.8,
    reviewCount: 62,
    tags: ['model', 'photo', 'ski'],
    bio: 'Adventure model and lifestyle content creator with 120k+ IG. Specializes in alpine fashion, brand activations, and powder skiing editorials. Huge personal archive of ski gear.',
    gear: [
      'Personal wardrobe archive',
      'On-piste & backcountry ski setup',
      'Snowboard setup available',
      '120k Instagram / 80k TikTok',
    ],
    rates: { halfDay: 350, fullDay: 650 },
    schedule: [false, false, false, false, false, false, false],
  },
  {
    id: 4,
    name: 'Tyler Park',
    initials: 'TP',
    primaryTag: 'video',
    lat: 39.040,
    lng: -120.050,
    location: 'Kings Beach, CA',
    rating: 4.7,
    reviewCount: 118,
    tags: ['snowboard', 'ski', 'video'],
    bio: 'Cinematic ski and snowboard filmmaker specializing in slow-motion powder shots, sunset laps, and resort B-roll. Quick turnaround edits for brands and athletes.',
    gear: [
      'Sony FX3 (main camera)',
      'Zeiss CP.3 Cinema primes',
      'DJI RS 3 Pro',
      'Aputure 600D (lighting)',
      'Phantom Flex 4K (rental, on request)',
    ],
    rates: { halfDay: 500, fullDay: 950 },
    schedule: [true, false, true, true, false, true, true],
  },
  {
    id: 5,
    name: 'Luna Vásquez',
    initials: 'LV',
    primaryTag: 'drone',
    lat: 38.685,
    lng: -120.070,
    location: 'Kirkwood, CA',
    rating: 4.9,
    reviewCount: 34,
    tags: ['drone', 'off-road', 'photo'],
    bio: 'Landscape and adventure drone pilot. Covers remote Sierran terrain, off-road expeditions, and desert rallies from above. Hyperlapse and time-lapse specialist.',
    gear: [
      'DJI Mavic 3 Classic (landscape)',
      'Autel EVO Nano+ (travel)',
      'Sony ZV-E1 (ground video)',
      'Sony A6700 (stills)',
      'Laowa 10mm Zero-D',
    ],
    rates: { halfDay: 550, fullDay: 1000 },
    schedule: [true, true, true, false, true, false, true],
  },
  {
    id: 6,
    name: 'Kai Brooks',
    initials: 'KB',
    primaryTag: 'photo',
    lat: 39.327,
    lng: -120.183,
    location: 'Truckee, CA',
    rating: 4.8,
    reviewCount: 201,
    tags: ['photo', 'video', 'off-road', 'snowboard'],
    bio: 'All-mountain shooter with 8 years covering everything from pow days to desert off-road rallies. Fast, versatile, and low-fuss. Published in Powder, Freeskier, and 4x4 Magazine.',
    gear: [
      'Nikon Z9 (primary)',
      'Nikon Z6 III (secondary)',
      'Nikkor 14–24mm f/2.8 S',
      'Nikkor 70–200mm f/2.8 VR S',
      'Full ND / CPL filter kit',
    ],
    rates: { halfDay: 400, fullDay: 750 },
    schedule: [true, true, false, true, true, true, false],
  },
  {
    id: 7,
    name: 'Patrick Yun',
    initials: 'PY',
    primaryTag: 'video',
    lat: 39.328,
    lng: -120.232,
    location: 'Truckee, CA',
    rating: 5.0,
    reviewCount: 1,
    tags: ['video', 'snowboard', 'off-road'],
    bio: 'Snowboard filmer and content creator based in Truckee. Sony FX3 shooter with a DJI RS3 gimbal. Off-road capable — Tacoma TRD gets me anywhere in the Sierra. Founder of Shutter.',
    gear: ['Sony FX3', 'DJI RS3 gimbal', 'Premiere Pro', 'Tacoma TRD — off-road', 'GoPro Hero 12'],
    rates: { halfDay: 400, fullDay: 700 },
    schedule: [true, true, true, true, true, true, true],
  },
];
